import Head from "next/head";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Titulo from "@/components/Titulo";
import Buscador from "@/components/Buscador";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Noticias</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Titulo></Titulo>
      <h1 style={{textAlign: "center", padding: "2rem"}}>Imagen aqui</h1>
      <Buscador></Buscador>
      <Footer></Footer>
    </>
  );
}
